version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  fastapi:
    image: registry.cn-hangzhou.aliyuncs.com/base_mj/vmbook:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      QWEN_API_KEY: ${QWEN_API_KEY}
      OSS_ENDPOINT: ${OSS_ENDPOINT}
      OSS_ACCESS_KEY_ID: ${OSS_ACCESS_KEY_ID}
      OSS_ACCESS_KEY_SECRET: ${OSS_ACCESS_KEY_SECRET}
      OSS_BUCKET_NAME: ${OSS_BUCKET_NAME}
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
