name: Gitee repos mirror periodic job

on:
  push:
    branches:
      - '**'
    paths:
      - '**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.01
      with:
        github_org: wmjjmwwmj  # 替换 src
        gitee_org: mjwei1126       # 替换 dst
        private_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # 替换 dst_key
        gitee_token: ${{ secrets.GITEE_TOKEN }}  # 这里的名称未明确，但可能应替换为 github_token 或 gitee_token
